name: Generate the OS information
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: "4.11.0"
    - run: opam pin add osinfo.dev -n .
    - name: External Dependencies
      run: opam depext -y osinfo
    - name: Dependencies
      run: opam install -t . --deps-only
    - name: Build
      run: opam exec -- dune build 
    - name: Generate
      run: opam exec -- dune gen/main.exe > ubuntu