name: Github OCaml-CI
on: [push, pull_request]
jobs:
  debian-10-ocaml-4_11:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:debian-10-ocaml-4.11
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: astring.0.8.5 base.v0.14.0 base-bigarray.base base-threads.base base-unix.base
        cmdliner.1.0.4 conf-m4.1 cppo.1.6.7 csexp.1.3.2 dune.2.7.1 dune-build-info.2.7.1
        dune-configurator.2.7.1 fix.20201120 fmt.0.8.9 fpath.0.7.3 menhir.20201216
        menhirLib.20201216 menhirSdk.20201216 num.1.4 ocaml.4.11.1 ocaml-base-compiler.4.11.1
        ocaml-compiler-libs.v0.12.3 ocaml-config.1 ocaml-migrate-parsetree.2.1.0 ocaml-version.3.0.0
        ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlformat.0.16.0 ocamlgraph.2.0.0 odoc.1.5.2
        opam-core.2.1.0~beta2 opam-file-format.2.1.1 opam-format.2.1.0~beta2 opam-repository.2.1.0~beta2
        opam-state.2.1.0~beta2 parsexp.v0.14.0 ppx_derivers.1.2.1 ppxlib.0.20.0 re.1.9.0
        result.1.5 seq.base sexplib.v0.14.0 sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0
        topkg.1.0.3 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuseg.13.0.0 uutf.1.0.2
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e a21a4146c88a6c420f3b9df613c75376ba594e99
        || git fetch origin master) && git reset -q --hard a21a4146c88a6c420f3b9df613c75376ba594e99
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn osinfo.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y osinfo.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  alpine-3_12-ocaml-4_11:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:alpine-3.12-ocaml-4.11
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: astring.0.8.5 base.v0.14.0 base-bigarray.base base-threads.base base-unix.base
        cmdliner.1.0.4 conf-m4.1 cppo.1.6.7 csexp.1.3.2 dune.2.7.1 dune-build-info.2.7.1
        dune-configurator.2.7.1 fix.20201120 fmt.0.8.9 fpath.0.7.3 menhir.20201216
        menhirLib.20201216 menhirSdk.20201216 num.1.4 ocaml.4.11.1 ocaml-base-compiler.4.11.1
        ocaml-compiler-libs.v0.12.3 ocaml-config.1 ocaml-migrate-parsetree.2.1.0 ocaml-version.3.0.0
        ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlformat.0.16.0 ocamlgraph.2.0.0 odoc.1.5.2
        opam-core.2.1.0~beta2 opam-file-format.2.1.1 opam-format.2.1.0~beta2 opam-repository.2.1.0~beta2
        opam-state.2.1.0~beta2 parsexp.v0.14.0 ppx_derivers.1.2.1 ppxlib.0.20.0 re.1.9.0
        result.1.5 seq.base sexplib.v0.14.0 sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0
        topkg.1.0.3 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuseg.13.0.0 uutf.1.0.2
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e a21a4146c88a6c420f3b9df613c75376ba594e99
        || git fetch origin master) && git reset -q --hard a21a4146c88a6c420f3b9df613c75376ba594e99
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn osinfo.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y osinfo.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  ubuntu-18_04-ocaml-4_11:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:ubuntu-18.04-ocaml-4.11
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: astring.0.8.5 base.v0.14.0 base-bigarray.base base-threads.base base-unix.base
        cmdliner.1.0.4 conf-m4.1 cppo.1.6.7 csexp.1.3.2 dune.2.7.1 dune-build-info.2.7.1
        dune-configurator.2.7.1 fix.20201120 fmt.0.8.9 fpath.0.7.3 menhir.20201216
        menhirLib.20201216 menhirSdk.20201216 num.1.4 ocaml.4.11.1 ocaml-base-compiler.4.11.1
        ocaml-compiler-libs.v0.12.3 ocaml-config.1 ocaml-migrate-parsetree.2.1.0 ocaml-version.3.0.0
        ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlformat.0.16.0 ocamlgraph.2.0.0 odoc.1.5.2
        opam-core.2.1.0~beta2 opam-file-format.2.1.1 opam-format.2.1.0~beta2 opam-repository.2.1.0~beta2
        opam-state.2.1.0~beta2 parsexp.v0.14.0 ppx_derivers.1.2.1 ppxlib.0.20.0 re.1.9.0
        result.1.5 seq.base sexplib.v0.14.0 sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0
        topkg.1.0.3 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuseg.13.0.0 uutf.1.0.2
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e a21a4146c88a6c420f3b9df613c75376ba594e99
        || git fetch origin master) && git reset -q --hard a21a4146c88a6c420f3b9df613c75376ba594e99
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn osinfo.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y osinfo.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  opensuse-15_2-ocaml-4_11:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:opensuse-15.2-ocaml-4.11
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: astring.0.8.5 base.v0.14.0 base-bigarray.base base-threads.base base-unix.base
        cmdliner.1.0.4 conf-m4.1 cppo.1.6.7 csexp.1.3.2 dune.2.7.1 dune-build-info.2.7.1
        dune-configurator.2.7.1 fix.20201120 fmt.0.8.9 fpath.0.7.3 menhir.20201216
        menhirLib.20201216 menhirSdk.20201216 num.1.4 ocaml.4.11.1 ocaml-base-compiler.4.11.1
        ocaml-compiler-libs.v0.12.3 ocaml-config.1 ocaml-migrate-parsetree.2.1.0 ocaml-version.3.0.0
        ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlformat.0.16.0 ocamlgraph.2.0.0 odoc.1.5.2
        opam-core.2.1.0~beta2 opam-file-format.2.1.1 opam-format.2.1.0~beta2 opam-repository.2.1.0~beta2
        opam-state.2.1.0~beta2 parsexp.v0.14.0 ppx_derivers.1.2.1 ppxlib.0.20.0 re.1.9.0
        result.1.5 seq.base sexplib.v0.14.0 sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0
        topkg.1.0.3 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuseg.13.0.0 uutf.1.0.2
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e a21a4146c88a6c420f3b9df613c75376ba594e99
        || git fetch origin master) && git reset -q --hard a21a4146c88a6c420f3b9df613c75376ba594e99
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn osinfo.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y osinfo.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  centos-8-ocaml-4_11:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:centos-8-ocaml-4.11
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: astring.0.8.5 base.v0.14.0 base-bigarray.base base-threads.base base-unix.base
        cmdliner.1.0.4 conf-m4.1 cppo.1.6.7 csexp.1.3.2 dune.2.7.1 dune-build-info.2.7.1
        dune-configurator.2.7.1 fix.20201120 fmt.0.8.9 fpath.0.7.3 menhir.20201216
        menhirLib.20201216 menhirSdk.20201216 num.1.4 ocaml.4.11.1 ocaml-base-compiler.4.11.1
        ocaml-compiler-libs.v0.12.3 ocaml-config.1 ocaml-migrate-parsetree.2.1.0 ocaml-version.3.0.0
        ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlformat.0.16.0 ocamlgraph.2.0.0 odoc.1.5.2
        opam-core.2.1.0~beta2 opam-file-format.2.1.1 opam-format.2.1.0~beta2 opam-repository.2.1.0~beta2
        opam-state.2.1.0~beta2 parsexp.v0.14.0 ppx_derivers.1.2.1 ppxlib.0.20.0 re.1.9.0
        result.1.5 seq.base sexplib.v0.14.0 sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0
        topkg.1.0.3 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuseg.13.0.0 uutf.1.0.2
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: cd ~/opam-repository && (git cat-file -e a21a4146c88a6c420f3b9df613c75376ba594e99
        || git fetch origin master) && git reset -q --hard a21a4146c88a6c420f3b9df613c75376ba594e99
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn osinfo.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y osinfo.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  fedora-32-ocaml-4_11:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:fedora-32-ocaml-4.11
      env:
        HOME: /home/opam
      options: --user 1000
    env:
      HOME: /home/opam
      DEPS: astring.0.8.5 base.v0.14.0 base-bigarray.base base-threads.base base-unix.base
        cmdliner.1.0.4 conf-m4.1 cppo.1.6.7 csexp.1.3.2 dune.2.7.1 dune-build-info.2.7.1
        dune-configurator.2.7.1 fix.20201120 fmt.0.8.9 fpath.0.7.3 menhir.20201216
        menhirLib.20201216 menhirSdk.20201216 num.1.4 ocaml.4.11.1 ocaml-base-compiler.4.11.1
        ocaml-compiler-libs.v0.12.3 ocaml-config.1 ocaml-migrate-parsetree.2.1.0 ocaml-version.3.0.0
        ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlformat.0.16.0 ocamlgraph.2.0.0 odoc.1.5.2
        opam-core.2.1.0~beta2 opam-file-format.2.1.1 opam-format.2.1.0~beta2 opam-repository.2.1.0~beta2
        opam-state.2.1.0~beta2 parsexp.v0.14.0 ppx_derivers.1.2.1 ppxlib.0.20.0 re.1.9.0
        result.1.5 seq.base sexplib.v0.14.0 sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0
        topkg.1.0.3 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuseg.13.0.0 uutf.1.0.2
    defaults:
      run:
        working-directory: /home/opam
    steps:
    - run: sudo dnf install -y findutils
    - run: cd ~/opam-repository && (git cat-file -e a21a4146c88a6c420f3b9df613c75376ba594e99
        || git fetch origin master) && git reset -q --hard a21a4146c88a6c420f3b9df613c75376ba594e99
        && git log --no-decorate -n1 --oneline && opam update -u
    - run: mkdir -p /home/opam/package
    - run: git clone https://github.com/$GITHUB_REPOSITORY . && git checkout $GITHUB_SHA
      working-directory: /home/opam/package
    - run: opam pin add -yn osinfo.dev "./"
      working-directory: /home/opam/package
    - run: opam depext --update -y osinfo.dev $DEPS
      working-directory: /home/opam/package
    - run: opam install $DEPS
      working-directory: /home/opam/package
    - run: opam exec -- dune build @install @runtest && rm -rf _build
      working-directory: /home/opam/package
  homebrew-latest-ocaml-4_11:
    strategy:
      matrix:
        operating-system: [macos-latest]
        ocaml-version: [4.11.1]
    runs-on: ${{ matrix.operating-system }}
    env:
      DEPS: astring.0.8.5 base.v0.14.0 base-bigarray.base base-threads.base base-unix.base
        cmdliner.1.0.4 conf-m4.1 cppo.1.6.7 csexp.1.3.2 dune.2.7.1 dune-build-info.2.7.1
        dune-configurator.2.7.1 fix.20201120 fmt.0.8.9 fpath.0.7.3 menhir.20201216
        menhirLib.20201216 menhirSdk.20201216 num.1.4 ocaml.4.11.1 ocaml-base-compiler.4.11.1
        ocaml-compiler-libs.v0.12.3 ocaml-config.1 ocaml-migrate-parsetree.2.1.0 ocaml-version.3.0.0
        ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlformat.0.16.0 ocamlgraph.2.0.0 odoc.1.5.2
        opam-core.2.1.0~beta2 opam-file-format.2.1.1 opam-format.2.1.0~beta2 opam-repository.2.1.0~beta2
        opam-state.2.1.0~beta2 parsexp.v0.14.0 ppx_derivers.1.2.1 ppxlib.0.20.0 re.1.9.0
        result.1.5 seq.base sexplib.v0.14.0 sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0
        topkg.1.0.3 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuseg.13.0.0 uutf.1.0.2
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin add -yn osinfo.dev "./"
    - run: opam depext --update -yt osinfo.dev
    - run: opam list --short --columns=package > installed.deps; for dep in $DEPS;
        do [[ ! "$dep" =~ $(echo ^\($(paste -sd'|' installed.deps)\)$) && ! "$dep"
        = "ocaml."* && ! "$dep" = "ocaml-base-compiler."* ]] && export NEW_DEPS="$dep
        $NEW_DEPS"; done; echo $NEW_DEPS; opam install $NEW_DEPS
    - run: opam exec -- dune build @install @runtest && rm -rf _build
  windows-latest-ocaml-4_11:
    strategy:
      matrix:
        operating-system: [windows-latest]
        ocaml-version: [4.11.1]
    runs-on: ${{ matrix.operating-system }}
    env:
      DEPS: astring.0.8.5 base.v0.14.0 base-bigarray.base base-threads.base base-unix.base
        cmdliner.1.0.4 conf-m4.1 cppo.1.6.7 csexp.1.3.2 dune.2.7.1 dune-build-info.2.7.1
        dune-configurator.2.7.1 fix.20201120 fmt.0.8.9 fpath.0.7.3 menhir.20201216
        menhirLib.20201216 menhirSdk.20201216 num.1.4 ocaml.4.11.1 ocaml-base-compiler.4.11.1
        ocaml-compiler-libs.v0.12.3 ocaml-config.1 ocaml-migrate-parsetree.2.1.0 ocaml-version.3.0.0
        ocamlbuild.0.14.0 ocamlfind.1.8.1 ocamlformat.0.16.0 ocamlgraph.2.0.0 odoc.1.5.2
        opam-core.2.1.0~beta2 opam-file-format.2.1.1 opam-format.2.1.0~beta2 opam-repository.2.1.0~beta2
        opam-state.2.1.0~beta2 parsexp.v0.14.0 ppx_derivers.1.2.1 ppxlib.0.20.0 re.1.9.0
        result.1.5 seq.base sexplib.v0.14.0 sexplib0.v0.14.0 stdio.v0.14.0 stdlib-shims.0.1.0
        topkg.1.0.3 tyxml.4.4.0 uchar.0.0.2 uucp.13.0.0 uuseg.13.0.0 uutf.1.0.2
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - run: opam pin add -yn osinfo.dev "./"
    - run: opam depext --update -yt osinfo.dev
    - run: opam list --short --columns=package > installed.deps; for dep in $DEPS;
        do [[ ! "$dep" =~ $(echo ^\($(paste -sd'|' installed.deps)\)$) && ! "$dep"
        = "ocaml."* && ! "$dep" = "ocaml-base-compiler."* ]] && export NEW_DEPS="$dep
        $NEW_DEPS"; done; echo $NEW_DEPS; opam install $NEW_DEPS
    - run: opam exec -- dune build @install @runtest && rm -rf _build
